name: Test Danser Functionality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-danser:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      actions: write
      checks: write

    container:
      image: ghcr.io/${{ github.repository }}:latest
      options: --user root

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy files to required locations
        run: |
          mkdir -p /app/source
          cp -r . /app/source/

      - name: Create danser configuration
        run: |
          mkdir -p /home/danser/.danser
          cat > /home/danser/.danser/settings.json << EOF
          {
            "General": {
              "OsuSongsDir": "/app/songs",
              "OsuReplaysDir": "/app"
            },
            "Recording": {
              "Encoder": "libx264",
              "PixelFormat": "yuv420p",
              "FPS": 60,
              "Width": 1920,
              "Height": 1080,
              "OutputDir": "/app/output"
            }
          }
          EOF

      - name: Set up directories
        run: |
          mkdir -p /app/songs
          mkdir -p /app/output
          cp /app/source/songs/* /app/songs/ || true
          cp /app/source/replay.osr /app/ || true

      - name: Check for GTK library and ldconfig
        run: |
          echo "--- Checking for libgtk-3.so.0 ---"
          find /usr/lib -name "libgtk-3.so.0"
          echo "--- Checking ldconfig cache ---"
          ldconfig -p | grep libgtk || echo "libgtk not found in ldconfig cache"
          echo "--- Checking LD_LIBRARY_PATH ---"
          echo $LD_LIBRARY_PATH

      - name: Test danser functionality
        env:
          LD_LIBRARY_PATH: /usr/local/lib
        run: |
          # Run danser with the replay
          danser-go -settings /home/danser/.danser -replay replay.osr -out test.mp4

      - name: Upload output video
        uses: actions/upload-artifact@v4
        with:
          name: danser-output
          path: /app/output/test.mp4 