name: Test Danser Functionality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-danser:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      actions: write
      checks: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: source

      - name: Run danser in container
        run: |
          docker run --rm \
            -v "$(pwd)/source/songs:/app/songs" \
            -v "$(pwd)/source/replay.osr:/app/replay.osr" \
            -v "$(pwd)/output:/app/output" \
            ghcr.io/${{ github.repository }}:latest \
            -replay replay.osr -out test.mp4

      - name: Upload output video
        uses: actions/upload-artifact@v4
        with:
          name: danser-output
          path: output/test.mp4 