name: Test Danser Functionality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-danser:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        danser_version: ['0.11.0', '0.10.0', '0.9.0']
      fail-fast: false
    permissions:
      contents: read
      packages: read
      actions: write
      checks: write

    container:
      image: docker.io/phantomic/danser-docker:${{ matrix.danser_version }}
      options: --user root

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Prevent git from changing line endings, which can affect hashes
          autocrlf: 'false'

      - name: Create danser directories
        run: |
          mkdir -p /app/settings
          mkdir -p /github/home/.osu/Songs
          mkdir -p /app/skins
          mkdir -p /app/output

      - name: Copy and verify CI settings file
        run: |
          cp -v .github/ci-settings.json /app/settings/settings.json
          chown -R danser:danser /app/settings
          ls -la /app/settings/
          cat /app/settings/settings.json

      - name: Set up songs
        run: |
          # Copy songs to the osu songs directory
          cp -rv songs/* /github/home/.osu/Songs/ || echo "No songs to copy"
          chown -R danser:danser /github/home/.osu
          
          echo "--- Listing Songs directory contents ---"
          ls -R /github/home/.osu/Songs/
          
          echo "--- Copying replay ---"
          cp -v replay.osr /app/ || echo "No replay to copy"
          chown danser:danser /app/replay.osr || true

      - name: Test danser functionality
        env:
          LD_LIBRARY_PATH: /usr/local/lib
        run: |
          # Run danser-cli within a virtual display server
          cd /app && xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" \
          ./danser-cli -settings /app/settings/settings.json -replay replay.osr -out output/test.mp4

      - name: Upload output video
        uses: actions/upload-artifact@v4
        with:
          name: danser-output-${{ matrix.danser_version }}
          path: /app/output/test.mp4 